=== vietanhit97/BTL_XML/BTL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="DSSanPham">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sanpham" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int" />
                            <xs:element name="name">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="3" />
                                        <xs:maxLength value="50" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Category_id">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minExclusive value="0" />
                                        <xs:maxExclusive value="10" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="desscription">
                                <xs:simpleType >
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9]{1,128}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="amount">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="0" />
                                        <xs:maxInclusive value="9999" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="price">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="100" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="size"/>
                            <xs:element name="image" >
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="type" use="optional">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value=".jpg"/>
                                                        <xs:enumeration value=".jepg"/>
                                                        <xs:enumeration value=".png"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="date" type="xs:dateTime" minOccurs="0"  maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType> 
        
        <xs:unique name="unique_id">
            <xs:selector xpath=".//*"/>
            <xs:field xpath="id"/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== vietanhit97/BTL_XML/BTL.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="BTL.xsl"?>
<DSSanPham 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="BTL.xsd">
    <Sanpham>
        <id>1</id>
        <name>Áo sơ mi</name>
        <Category_id>1</Category_id>
        <desscription>abc</desscription>
        <amount>100</amount>
        <price>1000000</price>
        <size>M</size>
        <image type=".jpg">a</image>
    </Sanpham>
    <Sanpham>
        <id>2</id>
        <name>Quần bò</name>
        <Category_id>2</Category_id>
        <desscription>12312vxvxcv</desscription>
        <amount>1000</amount>      
        <price>1000000</price>
        <size>M</size>
        <image type=".jpg">Anh</image> 
    </Sanpham>    
    <Sanpham>
        <id>3</id>
        <name>Quần âu</name>
        <Category_id>3</Category_id>
        <desscription>12312vxvxcv</desscription>
        <amount>1000</amount>
        <price>200000</price>
        <size>XL</size>
        <image type=".jpg">anh</image>
    </Sanpham>
    <Sanpham>
        <id>4</id>
        <name>Quần ngố</name>
        <Category_id>4</Category_id>
        <desscription>12312vxvxcv</desscription>
        <amount>0</amount> 
        <price>100000000</price>
        <size>XXL</size>
        <image type=".jpg">anh</image>
    </Sanpham>   

</DSSanPham>
